name: Commit Message Validation
on:
  - pull_request
jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # disabling git shallow clone - this is required for commitlint
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Commitlint
        run: |
          npm i @commitlint/cli@17
          npm i @commitlint/config-conventional@17
      - name: Check Commit Messages
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
