name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20"
      - name: Install Semantic Release
        run: |
          npm i semantic-release@21
          npm i conventional-changelog-conventionalcommits@5
          npm i @semantic-release/commit-analyzer@9
          npm i @semantic-release/release-notes-generator@11
          npm i @semantic-release/changelog@6
          npm i @semantic-release/npm@10
          npm i @semantic-release/git@10
          npm i @semantic-release/github@8
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npx semantic-release
      - name: Install Visual Studio Code Extension Manager
        run: npm i @vscode/vsce@2
      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish -p ${{ secrets.VISUAL_STUDIO_MARKETPLACE_PAT }}
